name: jobactions/update-dependencies
outputs:
  branch:
    description: Name of the branch created for the PR to merge the changes
    value:  ${{ steps.create-branch.outputs.branch }}
runs:
  using: composite
  steps:
  - uses: kagekirin/gha-utils/.github/actions/install-prerequisites@main
  - uses: kagekirin/gha-utils/.github/actions/install-version-tools@main
  - id: create-branch
    shell: pwsh
    run: |-
      $branch = "build/update-dependencies-${{ github.run_id }}"
      git checkout -b ${branch}
      echo "branch=${branch}" >> $Env:GITHUB_OUTPUT
  - id: update-dependencies
    shell: pwsh
    run: |-
      $ErrorActionPreference = 'Continue'
      foreach (${project} in @(fdfind "\.csproj$"))
      {
        echo "updating ${project}"
        foreach (${package} in @(xq -x "//ItemGroup/PackageReference/@Include" ${project}))
        {
          echo "updating ${package} in ${project}"
          try
          {
            dotnet add ${project} package ${package} --prerelease
            $newVersion = (xq -x "//ItemGroup/PackageReference[@Include='${package}']/@Version" ${project})
            git add ${project}
            git commit -m "build \(${project}\): update dependency ${package} to $newVersion"
          }
          catch
          {
            echo "Nothing to commit for ${project} referencing ${package}"
          }
          echo "done updating ${package} in ${project}"
        }
        echo "done updating ${project}"
      }
      echo "done updating all dependencies"
