name: jobactions/tag
inputs:
  prerelease:
    description: version '-prerelease.num' part
    required: false
    default: ''
  buildmeta:
    description: version '+buildmeta.text' part
    required: false
    default: ''
outputs:
  version:
    description: updated tag/version
    value: ${{ steps.update-git-tag.outputs.version }}
runs:
  using: composite
  steps:
  - uses: kagekirin/gha-utils/.github/actions/install-prerequisites@main
  - uses: kagekirin/gha-utils/.github/actions/install-version-tools@main
  - id: update-package-tag
    shell: pwsh
    run: |-
      $tag = @(csproj-version bump --patch NuGettier/NuGettier.csproj | rg -o '\d+\.\d+\.\d+')
      echo "tag=$tag"
      echo "tag=$tag" >> $Env:GITHUB_OUTPUT
  - id: update-git-tag
    uses: kagekirin/gha-utils/.github/actions/tag-generate@main
    with:
      version: ${{ steps.update-package-tag.outputs.tag }}
      prerelease: ${{ inputs.prerelease }}
      buildmeta: ${{ inputs.buildmeta }}
      add-revcount: ${{ inputs.prerelease != '' }}
  - shell: pwsh
    run: |-
      git config --local user.name "CI Bot [on behalf of Chris Helmich]"
      git config --local user.email kagekirin+gha@gmail.com
      git --no-pager status
      git --no-pager tag -l --sort=-v:refname | head -n 1

      $mmpr_regex = '^(?<major>0|[1-9]\d*)\.(?<minor>0|[1-9]\d*)\.(?<patch>0|[1-9]\d*)\.(?<revision>0|[1-9]\d*)'
      $version = "${{ steps.update-git-tag.outputs.version }}"
      echo "Version: $version"

      foreach ($project in @(fdfind "csproj$"))
      {
        $assemblyRevision = "$(git rev-list --all --count -- $(Split-Path -Parent $project))"
        $fileRevision = "$(git rev-list --all --count -- $project)"
        $assemblyVersion = "$version.$assemblyRevision"
        $fileVersion = "$version.$fileRevision"
        echo "patching $project"
        echo "assembly version: $assemblyVersion"
        echo "file version: $fileVersion"

        csproj-version set --version $version $project
        csproj-version set --version $assemblyVersion --xpath '//PropertyGroup/AssemblyVersion' --regex $mmpr_regex $project
        csproj-version set --version $fileVersion     --xpath '//PropertyGroup/FileVersion'     --regex $mmpr_regex $project
        git add $project
      }

      git commit -am "build (ci): update version to $version"
      git tag -f v$version

      git --no-pager tag -l --sort=-v:refname | head -n 1
      echo "version=$version" >> $Env:GITHUB_OUTPUT
