name: Install NuGettier
description: >-
  GitHub Action to install NuGettier

inputs:
  accept-license:
    description: "[YES|NO] Must be set explicitly to 'YES' to accept the license. Install won't proceed without."
    required: false
    default: NO


runs:
  using: composite
  steps:
  - name: Display license
    shell: bash
    run: |-
      echo "By running this installation script"
      echo "you automatically agree to the license terms of this Software Product"
      echo ""
      curl -s https://raw.githubusercontent.com/KageKirin/NuGettier/main/LICENSE
  - name: Install
    shell: bash
    run: |-
      dotnet tool install NuGettier -g --prerelease
      curl -LO https://github.com/KageKirin/NuGettier/blob/main/appconfig.json
      echo '$HOME/.dotnet/tools' >> $GITHUB_PATH

  - name: Verify installation
    shell: bash
    run: |-
      echo $PATH
      which dotnet-nugettier
      dotnet nugettier --version
