name: Install NuGettier
description: >-
  GitHub Action to install NuGettier

inputs:
  accept-license:
    description: "[YES|NO] Must be set explicitly to 'YES' to accept the license. Install won't proceed without."
    required: false
    default: NO


runs:
  using: composite
  steps:
  - name: Display license
    shell: bash
    run: |-
      curl -s https://raw.githubusercontent.com/KageKirin/NuGettier/main/LICENSE

  - name: Check license acceptation
    shell: bash
    run: |-
      accept=${{ inputs.accept-license }}
      if [ "${accept,,}" == "yes" ]; then
        echo "Thank you for accepting the license terms."
        echo "Installation can proceed."
        exit 0
      else
        echo "Sorry, but you have to explicitly accept the license terms"
        echo "by setting accept-license to 'yes'."
        echo "Installation cannot proceed"
        exit 1
      fi

  - name: Install
    shell: bash
    run: |-
      [ ! -f ".config/dotnet-tools.json" ] && dotnet new tool-manifest

      dotnet tool install NuGettier --prerelease
      curl -LO https://github.com/KageKirin/NuGettier/blob/main/appconfig.json

  - name: Verify installation
    shell: bash
    run: |-
      which dotnet-nugettier
      dotnet nugettier --version
